recipez/urls.py
from django.urls import path
from recipez import views

app_name = 'recipez'
urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/<recipe_id>/', views.show_recipe, name='show_recipe'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('user_profile/<user_name>/', views.user_profile, name='user_profile'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('logout/', views.user_logout, name='logout'),
    path('like/<recipe_id>/', views.like_recipe, name='like_recipe'),
    path('add_bookmark/<recipe_id>/', views.add_bookmark, name='add_bookmark'),
]

recipez_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipez import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from recipez_project.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('', views.index, name='index'),
    path('recipez/', include('recipez.urls')),
    path("admin/", admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipze_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipez import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', views.index, name='index'),
                  path('recipez/', include('recipez.urls')),
                  path("admin/", admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipez/models.py
from django.db import models
from django.contrib.auth.models import User

MAX_LENGTH = 128


class UserProfile(models.Model):
    # includes username, password, email
    user = models.OneToOneField(
        User,
        related_name='user_profile',
        on_delete=models.CASCADE
    )

    # List of recipe_id
    bookmark = models.JSONField(null=True, blank=True)

    creation_time = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    avatar = models.ImageField(upload_to='profile_images', null=True, blank=True)

    # recipes

    def __str__(self):
        return self.user.username


class Ingredient(models.Model):
    name_and_amount = models.CharField(max_length=MAX_LENGTH, unique=True)

    def __str__(self):
        return self.name_and_amount


class Recipe(models.Model):
    user = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        related_name='recipes'
    )

    name = models.CharField(max_length=MAX_LENGTH)

    # Main dish, Starter, Drink, Dessert...etc
    category = models.CharField(max_length=MAX_LENGTH, default='None')

    # Chinese, Japanese, Korean, American, Indian...etc
    region = models.CharField(max_length=MAX_LENGTH, default='None')

    # Easy, Medium, Hard...etc
    difficulty = models.CharField(max_length=MAX_LENGTH)

    detail = models.TextField()
    photo = models.ImageField(upload_to='recipe_images', null=True, blank=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    average_rating = models.FloatField(default=0)
    is_active = models.BooleanField(default=True)
    cooking_duration = models.CharField(max_length=MAX_LENGTH)
    is_vegan = models.BooleanField(default=False)

    ingredients = models.ManyToManyField(
        Ingredient,
        related_name='recipes',
    )

    liked_users = models.ManyToManyField(
        UserProfile,
        related_name='liked_recipes',
    )

    def __str__(self):
        return self.name


class Comment(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    username = models.CharField(max_length=MAX_LENGTH)

    # 0.0 ~ 5.0
    rating = models.FloatField()

    creation_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    detail = models.TextField()

    def __str__(self):
        return self.detail

recipez/forms.py
from django import forms
from recipez.models import UserProfile, Comment, Ingredient, Recipe
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar',)
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
        }


class CustomFloatInput(forms.widgets.TextInput):
    input_type = 'number'
    template_name = 'django/forms/widgets/number.html'
    step = 'any'
    min_value = 0
    max_value = 5

    def __init__(self, *args, **kwargs):
        kwargs['attrs'] = {'class': 'form-control', 'step': self.step, 'min': self.min_value, 'max': self.max_value}
        super().__init__(*args, **kwargs)

    def validate(self, value):
        super().validate(value)
        if value is not None:
            if value < self.min_value or value > self.max_value:
                raise ValidationError(f'Enter a value between {self.min_value} and {self.max_value}.')


class CustomCommentWidget(forms.Textarea):
    def __init__(self, attrs=None):
        default_attrs = {'class': 'form-control me-2', 'style': 'background: #fff;', 'rows': '4'}
        if attrs:
            default_attrs.update(attrs)
        super().__init__(attrs=default_attrs)


class CommentForm(forms.ModelForm):
    detail = forms.CharField(widget=CustomCommentWidget())
    rating = forms.FloatField(widget=CustomFloatInput)

    # Provide additional information
    class Meta:
        # Association between the ModelForm and a model
        model = Comment
        fields = ('rating', 'detail')

class RecipeModelForm(forms.ModelForm):
    detail = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = Recipe
        fields = ['name', 'category', 'region', 'difficulty', 'cooking_duration', 'is_vegan', 'photo', 'detail']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.TextInput(attrs={'class': 'form-control text-muted', 'placeholder': 'Category'}),
            'region': forms.TextInput(attrs={'class': 'form-control text-muted', 'placeholder': 'Region'}),
            'difficulty': forms.TextInput(attrs={'class': 'form-control text-muted'}),
            'cooking_duration': forms.TextInput(attrs={'class': 'form-control'}),
            'is_vegan': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'detail': forms.Textarea(attrs={'class': 'form-control'}),
        }

recipez/views.py
# Import modules and functions
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse

from recipez.forms import UserForm, UserProfileForm, CommentForm, RecipeModelForm
from recipez.functions import search_by, is_ajax
from recipez.models import Recipe, UserProfile, Ingredient, Comment


# Create your views here.

# Home Page
def index(
    request, template='recipez/index/index.html', extra_context=None):
    if request.method == 'POST':
        search_content = request.POST.get('search_content')
        context_dict = search_by(search_content)
        return render(request, 'recipez/search.html', context=context_dict)
    RECIPE_PER_PAGE = 3
    page = int(request.GET.get('page', 1))

    # Enable Pagination for the recipe list
    recipe_list = Recipe.objects.all().order_by('-creation_time')
    p = paginator.Paginator(recipe_list, RECIPE_PER_PAGE)
    try:
        recipe_page = p.page(page)
    except paginator.EmptyPage:
        recipe_page = paginator.Page([], page, p)

    if not is_ajax(request):
        context_dict = {'author_list': None, 'recipe_list_by_Ingredient': None,
                        'recipe_list_by_RecipeName': recipe_page}
        best_pages = Recipe.objects.order_by('-likes')[:3]
        context_dict['best_of_today'] = best_pages
        return render(request,
                      'recipez/index/index.html',
                      context=context_dict
                      )

    elif is_ajax(request):
        content = ''
        page = int(request.GET.get('page'))
        try:
            recipe_page = p.page(page)
        except paginator.EmptyPage:
            recipe_page = paginator.Page([], page, p)

        for post in recipe_page:
            content += render_to_string('recipez/index/index_post_item.html',
                                        {'recipe': post},
                                        request=request)
        return JsonResponse({
            "content": content,
            "end_pagination": True if page >= p.num_pages else False,
        })


# Recipe Detail Page
def show_recipe(request, recipe_id):
    context_dict = {}
    # Form for receiving new comments of current user (request.user.username)
    form = CommentForm()
    context_dict['form'] = form

    try:
        recipe = Recipe.objects.get(id=recipe_id)  # recipe_id as a index to access to relevant data
        comments = Comment.objects.filter(recipe=recipe).order_by(
            '-creation_time')  # filter to get all data from the comments
        all_users = UserProfile.objects.all()

        context_dict['recipe'] = recipe
        context_dict['comments'] = comments
        context_dict['all_users'] = all_users
        context_dict['ingredients'] = recipe.ingredients.all()

        # check likes and bookmarks
        context_dict['is_liked'] = True
        context_dict['is_bookmark'] = 'Add to bookmark'
        if request.user.is_authenticated:
            u_profile = request.user.user_profile
            is_liked = u_profile.liked_recipes.filter(id=recipe_id)
            if is_liked.exists():
                context_dict['is_liked'] = True
            elif not is_liked.exists(): # if not liked
                context_dict['is_liked'] = False
            if request.user.user_profile.bookmark is None:
                u_profile.bookmark = []
                u_profile.save()
            else:
                if int(recipe_id) in request.user.user_profile.bookmark:
                    context_dict['is_bookmark'] = 'Already in bookmark'

        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.recipe = recipe
                comment.username = request.user.username
                comment.save()

                # update average_rating
                sum_ = 0
                for c in recipe.comments.all():
                    sum_ += c.rating
                recipe.average_rating = sum_ / recipe.comments.count()
                recipe.save()

    except Recipe.DoesNotExist:
        # We get here if we didn't find the specified recipe.
        context_dict['recipe'] = None
        context_dict['comments'] = None
        context_dict['all_users'] = None

    return render(request, 'recipez/recipe.html', context=context_dict)


# Post a new Recipe
def add_recipe(request):
    if request.method == 'POST':
        recipe_form = RecipeModelForm(request.POST)
        if recipe_form.is_valid():
            recipe = recipe_form.save(commit=False)
            recipe.user = request.user.user_profile
            if 'photo' in request.FILES:
                recipe.photo = request.FILES['photo']
            recipe.save()
            print("recipe saved")
            sum_ingredients = int(request.POST.get('ingredient_set-TOTAL_FORMS'))
            for i in range(0, sum_ingredients):
                ingredient_name = request.POST.get('ingredient_set-' + str(i) + '-ingredient')
                print(ingredient_name)
                ingredient = Ingredient.objects.get_or_create(name_and_amount=ingredient_name)[0]
                print(ingredient)
                ingredient.recipes.add(recipe)
                ingredient.save()
            print("ingredient saved")
            messages.success(request, "You have successfully added a new recipe!")
            return redirect(reverse('recipez:index'))

    else:
        recipe_form = RecipeModelForm()
    context = {
        'recipe_form': recipe_form,
    }
    return render(request, 'recipez/add_recipe.html', context)


# User Profile Page
def user_profile(request, user_name):
    user = User.objects.get(username=user_name)
    # userProfile = user.user_profile

    avatar = user.user_profile.avatar  # Get the user's avatar

    post_recipes = user.user_profile.recipes.all()  # Get the user's all posted recipes
    saved_recipes_id = user.user_profile.bookmark  # Get the user's saved recipes (list of recipe_id)

    saved_recipes = []
    if saved_recipes_id:
        for item_id in saved_recipes_id:
            saved_recipes.append(Recipe.objects.get(id = item_id))
    
    liked_recipes = user.user_profile.liked_recipes.all()
    
    context_dict = {
        'user_name': user_name,
        'user_avatar': avatar,
        'post_recipes': post_recipes,
        'saved_recipes': saved_recipes,
        'liked_recipes': liked_recipes,
    }

    return render(request, 'recipez/user_profile.html', context=context_dict)


# Login Page
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('usernameInput')
        password = request.POST.get('passwordInput')
        remember_me = request.POST.get('rememberMe')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                if not remember_me:
                    request.session.set_expiry(0)  # set session expire time to 0
                messages.success(request, "You have been successfully logged in!")
                return redirect(reverse('recipez:index'))
            else:
                return HttpResponse("Your Recipez account is disabled.")
        else:
            # print(f"Invalid login details: {username}, {password}") # Not required, only for debugging
            messages.error(request, f"Your login details are incorrect, {username}")
            return redirect(reverse('recipez:login'))

    else:
        return render(request, 'recipez/authentication/login.html')


# User Registration Form
def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

        if registered:
            messages.success(request, "You have been successfully registered! Please log in.")
            return redirect(reverse('recipez:login'))
        else:
            messages.error(request, "Please check your registration details.")
            return redirect(reverse('recipez:register'))
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }
    return render(request, 'recipez/authentication/register.html', context=context)


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, "Successfully logged out!")
    return redirect(reverse('recipez:index'))


@login_required
def like_recipe(request, recipe_id):
    if request.method == 'POST' and is_ajax(request):
        user_profile = request.POST.get('user')
        recipe = request.POST.get('recipe')
        print(user_profile, recipe)

        u_profile = request.user.user_profile
        target_recipe = Recipe.objects.get(id=recipe)
        is_liked = request.user.user_profile.liked_recipes.filter(id=recipe_id)

        if is_liked.exists():
            u_profile.liked_recipes.remove(target_recipe)
            target_recipe.likes -= 1
        else:

templates/recipez/add_recipe.html
{% extends 'recipez/includes/base.html' %}
{% load static %}

{% block title_block %}
    Add recipe
{% endblock %}

{% block head_block %}
<script type="text/javascript" src="{% static 'js/recipe.js' %}"></script>
{% endblock %}

{% block body_block %}

    <section class="h-100">
        <div class="container py-5">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col">
                    <div class="card my-4">
                        <div class="row g-0">
                            <div class="col-lg-4 col-xl-6 d-none d-xl-block position-relative">
                                <h2 class="m-5 position-absolute w-100 bg-dark text-white p-3" style="z-index: 1;">Write a New
                                    Recipe</h2>
                                <img src="https://cdn.pixabay.com/photo/2015/08/25/03/50/background-906135_960_720.jpg"
                                     alt="Image by kerdkanno on Freepik" class="img-fluid"
                                     style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem; object-fit: cover; height: 100%; filter: brightness(65%);"/>
                            </div>
                            <div class="col-lg-4 col-xl-6">
                                <div class="card-body p-md-5 bg-dark text-white">
                                    <div class="panel-body">
                                    <div class="form-outline w-100">
                                        <form class="row g-3" method="post" action="{% url 'recipez:add_recipe' %}"
                                              enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {% for field in recipe_form %}
                                                <div class="form-group">

                                                    <label>{{ field.label }}</label><br>{{ field }}

                                                    <span style="color: red">{{ field.errors.0 }}</span>
                                                </div>
                                            {% endfor %}
                                            <div id="ingredient-form">
                                                <button type="button" class="btn btn-block btn-outline-success" onClick="addNewIngredient()">New Ingredient
                                                </button>
                                                <script>
                                                </script>
                                            </div>
                                            <input type="hidden" name="ingredient_set-TOTAL_FORMS"
                                                   id="id_ingredient_set-TOTAL_FORMS"
                                                   value="{{ ingredient_forms|length }}">
                                            <div class="col-12">
                                                <button type="submit" onclick="submitIngredient()" class="col-md-8">Submit</button>
                                                <a href="{{request.get_full_path}}" class="btn btn-outline-danger">Reset</a>
                                            </div>
                                        </form>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/recipez/recipe.html
{% extends 'recipez/includes/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_block %}
{% endblock %}

{% block head_block %}
<script type="text/javascript" src="{% static 'js/recipe.js' %}"></script>
{% endblock %}

{% block body_block %}
    <section>
        <div class="container my-5 py-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 col-lg-10 col-xl-8">
                    <div class="card text-center">
                        <div class="card-header">
                            {% if recipe %}
                            <div class="d-flex flex-start align-items-center">
                                <!-- Recipe Creator -->
                                <img alt="{{ recipe.user.username }}'s profile image"
                                     class="rounded-circle shadow-1-strong me-3"
                                     src="{{ MEDIA_URL }}{{ recipe.user.avatar }}"
                                     width="50"/>
                                <div>
                                    <a class="navbar-brand" href="{% url 'recipez:user_profile' recipe.user %}"><h6 class="fw-bold text-primary mb-1">{{ recipe.user }}</h6></a>
                                    <!-- Recipe Creator -->
                                    <p class="text-muted small mb-0">
                                        {{ recipe.creation_time }}
                                    </p>
                                </div>
                            </div>
                            {% else %}
                                No author details.
                            {% endif %}
                        </div>
                        <div class="card-body">


                            <!-- Recipe Content -->
                        {% if recipe %}
                            <p class="mt-3 mb-4">
                            <h2>{{ recipe.name }}</h2>
                            <img src="{{ MEDIA_URL }}{{ recipe.photo }}"
                                 width="400"
                                 alt="{{ recipe.name }}'s image"/><br><br>
                            <small><b>Time:</b>&nbsp{{ recipe.cooking_duration }}</small>
                            <small><b>Level:</b>&nbsp{{ recipe.difficulty }}</small><br><br>
                            <small><b>Category:</b>&nbsp{{ recipe.category }}</small>
                            <small><b>Region:</b>&nbsp{{ recipe.region }}</small>
                            <small><b>Vegan:</b>&nbsp{{ recipe.is_vegan }}<br></small><br><br>

                            <b>Ingredients:</b>&nbsp<br><br>
                                {% if ingredients %}
                                    {% for ingredient in ingredients %}
                                        <li>{{ ingredient.name_and_amount }}</li>
                                    {% endfor %}
                                {% else %}
                                    No Ingredients.
                                {% endif %}<br><br>

                            <p><b>Methodology:</b>&nbsp<br><br>{{ recipe.detail }}</p>
                            <!-- Recipe Content -->
                            <div class="small d-flex justify-content-between">

                                <!-- Add likes -->
                                <div class="container row">
                                    <a id="likeButton" link="{% url 'recipez:like_recipe' recipe.id %}" user="{{user.username}}" recipe-id="{{recipe.id}}" if-liked="{{ is_liked }}">
                                        <div style="display: block;" id="heart">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="red" class="bi bi-heart" viewBox="0 0 16 16">
                                                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                                            </svg>
                                        </div>
                                        <div style="display: none;" id="heart-fill">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                                            </svg>
                                        </div>
                                    </a>
                                    <p class="lead" id="like-counter">{{ recipe.likes }}</p> 
                                </div>

                                <!-- Add to bookmark -->
                                <a href="{% url 'recipez:add_bookmark' recipe.id %}" class="btn btn-md btn-success">{{ is_bookmark }}</a>&nbsp;&nbsp;&nbsp;

                                <!-- Share recipe -->
                                <button class="btn btn-md btn-outline-secondary" onclick="copyUrl()">Share</button>

                            </div>
                        </div>

                        <div class="card-footer py-3 border-0" style="background-color: #f0f2f5;">
                            <br>
                            {% if comments %}
                                {% for comment in comments %}
                                    <div>
                                        <div class="card mb-4">
                                            <div class="card-body">
                                                {% if all_users %}
                                                    {% for user in all_users %}
                                                        {% if user.user.username == comment.username %}
                                                            <!-- Get User's avatar-->
                                                            <img alt="{{ user.user.username }}'s profile image"
                                                                 class="rounded-circle"
                                                                 src="{{ MEDIA_URL }}{{ user.user.user_profile.avatar }}"
                                                                 width="30">
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endif %}
                                                <p><b>{{ comment.username }}</b>&nbsp&nbsp{{ comment.creation_time }}</p>
                                                <p>{{ comment.rating }}</p>
                                                <p>{{ comment.detail }}</p>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% else %}
                                {# <strong>There are no comments present.</strong><br>#}
                            {% endif %}


                            <!-- Comments-->
                            {% if user.is_authenticated %}
                                <div class="card mb-4">
                                    <div class="card-body">
                                        <div class="d-flex flex-start w-100">
                                            <img class="rounded-circle shadow-1-strong me-3"
                                                 src="{{ MEDIA_URL }}{{ user.user_profile.avatar }}"
                                                 alt="{{ user.username }}'s profile image"
                                                 width="40"
                                                 height="40"/>
                                            <div class="form-outline w-100">
                                                <form id="comment_form" method="post"
                                                      action="{% url 'recipez:show_recipe' recipe.id %}">
                                                    {% csrf_token %}
                                                    {% for hidden in form.hidden_fields %}
                                                        {{ hidden }}
                                                    {% endfor %}
                                                    {% for field in form.visible_fields %}
                                                        {{ field.errors }}
                                                        {{ field.help_text }}
                                                        {% if field.name == 'rating' %}
                                                            <p>Rating:&nbsp</p>{{ field }}
                                                        {% elif field.name == 'detail' %}
                                                            <p>Comment:&nbsp</p>{{ field }}
                                                        {% endif %}
                                                    {% endfor %}
                                                    <div class="float-end mt-2 pt-1">
                                                        <button type="submit" class="btn btn-primary btn-sm"
                                                                name="submit"
                                                                value="Create comment">Post comment
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            <!-- Comments-->
                        </div>
                        {% else %}
                            No recipe details.
                        {% endif %}

                    </div>
                </div>
            </div>
    </section>
{% endblock %}