recipez/urls.py
from django.urls import path
from recipez import views

app_name = 'recipez'
urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/<recipe_id>/', views.show_recipe, name='show_recipe'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('user_profile/<user_name>/', views.user_profile, name='user_profile'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('logout/', views.user_logout, name='logout'),
    path('like/<recipe_id>/', views.like_recipe, name='like_recipe'),
    path('add_bookmark/<recipe_id>/', views.add_bookmark, name='add_bookmark'),
]

recipez_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipez import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from recipez_project.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('', views.index, name='index'),
    path('recipez/', include('recipez.urls')),
    path("admin/", admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipze_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipez import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', views.index, name='index'),
                  path('recipez/', include('recipez.urls')),
                  path("admin/", admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipez/models.py
from django.db import models
from django.contrib.auth.models import User

MAX_LENGTH = 128


class UserProfile(models.Model):
    # includes username, password, email
    user = models.OneToOneField(
        User,
        related_name='user_profile',
        on_delete=models.CASCADE
    )

    # List of recipe_id
    bookmark = models.JSONField(null=True, blank=True)

    creation_time = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    avatar = models.ImageField(upload_to='profile_images', null=True, blank=True)

    # recipes

    def __str__(self):
        return self.user.username


class Ingredient(models.Model):
    name_and_amount = models.CharField(max_length=MAX_LENGTH, unique=True)

    def __str__(self):
        return self.name_and_amount


class Recipe(models.Model):
    user = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        related_name='recipes'
    )

    name = models.CharField(max_length=MAX_LENGTH)

    # Main dish, Starter, Drink, Dessert...etc
    category = models.CharField(max_length=MAX_LENGTH, default='None')

    # Chinese, Japanese, Korean, American, Indian...etc
    region = models.CharField(max_length=MAX_LENGTH, default='None')

    # Easy, Medium, Hard...etc
    difficulty = models.CharField(max_length=MAX_LENGTH)

    detail = models.TextField()
    photo = models.ImageField(upload_to='recipe_images', null=True, blank=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    average_rating = models.FloatField(default=0)
    is_active = models.BooleanField(default=True)
    cooking_duration = models.CharField(max_length=MAX_LENGTH)
    is_vegan = models.BooleanField(default=False)

    ingredients = models.ManyToManyField(
        Ingredient,
        related_name='recipes',
    )

    liked_users = models.ManyToManyField(
        UserProfile,
        related_name='liked_recipes',
    )

    def __str__(self):
        return self.name


class Comment(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    username = models.CharField(max_length=MAX_LENGTH)

    # 0.0 ~ 5.0
    rating = models.FloatField()

    creation_time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    detail = models.TextField()

    def __str__(self):
        return self.detail

recipez/forms.py
from django import forms
from recipez.models import UserProfile, Comment, Ingredient, Recipe
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar',)
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
        }


class CustomFloatInput(forms.widgets.TextInput):
    input_type = 'number'
    template_name = 'django/forms/widgets/number.html'
    step = 'any'
    min_value = 0
    max_value = 5

    def __init__(self, *args, **kwargs):
        kwargs['attrs'] = {'class': 'form-control', 'step': self.step, 'min': self.min_value, 'max': self.max_value}
        super().__init__(*args, **kwargs)

    def validate(self, value):
        super().validate(value)
        if value is not None:
            if value < self.min_value or value > self.max_value:
                raise ValidationError(f'Enter a value between {self.min_value} and {self.max_value}.')


class CustomCommentWidget(forms.Textarea):
    def __init__(self, attrs=None):
        default_attrs = {'class': 'form-control me-2', 'style': 'background: #fff;', 'rows': '4'}
        if attrs:
            default_attrs.update(attrs)
        super().__init__(attrs=default_attrs)


class CommentForm(forms.ModelForm):
    detail = forms.CharField(widget=CustomCommentWidget())
    rating = forms.FloatField(widget=CustomFloatInput)

    # Provide additional information
    class Meta:
        # Association between the ModelForm and a model
        model = Comment
        fields = ('rating', 'detail')

class RecipeModelForm(forms.ModelForm):
    detail = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    class Meta:
        model = Recipe
        fields = ['name', 'category', 'region', 'difficulty', 'cooking_duration', 'is_vegan', 'photo', 'detail']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.TextInput(attrs={'class': 'form-control text-muted', 'placeholder': 'Category'}),
            'region': forms.TextInput(attrs={'class': 'form-control text-muted', 'placeholder': 'Region'}),
            'difficulty': forms.TextInput(attrs={'class': 'form-control text-muted'}),
            'cooking_duration': forms.TextInput(attrs={'class': 'form-control'}),
            'is_vegan': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'detail': forms.Textarea(attrs={'class': 'form-control'}),
        }

recipez/views.py
# Import modules and functions
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse

from recipez.forms import UserForm, UserProfileForm, CommentForm, RecipeModelForm
from recipez.functions import search_by, is_ajax
from recipez.models import Recipe, UserProfile, Ingredient, Comment


# Create your views here.

# Home Page
def index(
    request, template='recipez/index/index.html', extra_context=None):
    if request.method == 'POST':
        search_content = request.POST.get('search_content')
        context_dict = search_by(search_content)
        return render(request, 'recipez/search.html', context=context_dict)
    RECIPE_PER_PAGE = 3
    page = int(request.GET.get('page', 1))

    # Enable Pagination for the recipe list
    recipe_list = Recipe.objects.all().order_by('-creation_time')
    p = paginator.Paginator(recipe_list, RECIPE_PER_PAGE)
    try:
        recipe_page = p.page(page)
    except paginator.EmptyPage:
        recipe_page = paginator.Page([], page, p)

    if not is_ajax(request):
        context_dict = {'author_list': None, 'recipe_list_by_Ingredient': None,
                        'recipe_list_by_RecipeName': recipe_page}
        best_pages = Recipe.objects.order_by('-likes')[:3]
        context_dict['best_of_today'] = best_pages
        return render(request,
                      'recipez/index/index.html',
                      context=context_dict
                      )

    elif is_ajax(request):
        content = ''
        page = int(request.GET.get('page'))
        try:
            recipe_page = p.page(page)
        except paginator.EmptyPage:
            recipe_page = paginator.Page([], page, p)

        for post in recipe_page:
            content += render_to_string('recipez/index/index_post_item.html',
                                        {'recipe': post},
                                        request=request)
        return JsonResponse({
            "content": content,
            "end_pagination": True if page >= p.num_pages else False,
        })


# Recipe Detail Page
def show_recipe(request, recipe_id):
    context_dict = {}
    # Form for receiving new comments of current user (request.user.username)
    form = CommentForm()
    context_dict['form'] = form

    try:
        recipe = Recipe.objects.get(id=recipe_id)  # recipe_id as a index to access to relevant data
        comments = Comment.objects.filter(recipe=recipe).order_by(
            '-creation_time')  # filter to get all data from the comments
        all_users = UserProfile.objects.all()

        context_dict['recipe'] = recipe
        context_dict['comments'] = comments
        context_dict['all_users'] = all_users
        context_dict['ingredients'] = recipe.ingredients.all()

        # check likes and bookmarks
        context_dict['is_liked'] = True
        context_dict['is_bookmark'] = 'Add to bookmark'
        if request.user.is_authenticated:
            u_profile = request.user.user_profile
            is_liked = u_profile.liked_recipes.filter(id=recipe_id)
            if is_liked.exists():
                context_dict['is_liked'] = True
            elif not is_liked.exists(): # if not liked
                context_dict['is_liked'] = False
            if request.user.user_profile.bookmark is None:
                u_profile.bookmark = []
                u_profile.save()
            else:
                if int(recipe_id) in request.user.user_profile.bookmark:
                    context_dict['is_bookmark'] = 'Already in bookmark'

        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.recipe = recipe
                comment.username = request.user.username
                comment.save()

                # update average_rating
                sum_ = 0
                for c in recipe.comments.all():
                    sum_ += c.rating
                recipe.average_rating = sum_ / recipe.comments.count()
                recipe.save()

    except Recipe.DoesNotExist:
        # We get here if we didn't find the specified recipe.
        context_dict['recipe'] = None
        context_dict['comments'] = None
        context_dict['all_users'] = None

    return render(request, 'recipez/recipe.html', context=context_dict)


# Post a new Recipe
def add_recipe(request):
    if request.method == 'POST':
        recipe_form = RecipeModelForm(request.POST)
        if recipe_form.is_valid():
            recipe = recipe_form.save(commit=False)
            recipe.user = request.user.user_profile
            if 'photo' in request.FILES:
                recipe.photo = request.FILES['photo']
            recipe.save()
            print("recipe saved")
            sum_ingredients = int(request.POST.get('ingredient_set-TOTAL_FORMS'))
            for i in range(0, sum_ingredients):
                ingredient_name = request.POST.get('ingredient_set-' + str(i) + '-ingredient')
                print(ingredient_name)
                ingredient = Ingredient.objects.get_or_create(name_and_amount=ingredient_name)[0]
                print(ingredient)
                ingredient.recipes.add(recipe)
                ingredient.save()
            print("ingredient saved")
            messages.success(request, "You have successfully added a new recipe!")
            return redirect(reverse('recipez:index'))

    else:
        recipe_form = RecipeModelForm()
    context = {
        'recipe_form': recipe_form,
    }
    return render(request, 'recipez/add_recipe.html', context)


# User Profile Page
def user_profile(request, user_name):
    user = User.objects.get(username=user_name)
    # userProfile = user.user_profile

    avatar = user.user_profile.avatar  # Get the user's avatar

    post_recipes = user.user_profile.recipes.all()  # Get the user's all posted recipes
    saved_recipes_id = user.user_profile.bookmark  # Get the user's saved recipes (list of recipe_id)

    saved_recipes = []
    if saved_recipes_id:
        for item_id in saved_recipes_id:
            saved_recipes.append(Recipe.objects.get(id = item_id))
    
    liked_recipes = user.user_profile.liked_recipes.all()
    
    context_dict = {
        'user_name': user_name,
        'user_avatar': avatar,
        'post_recipes': post_recipes,
        'saved_recipes': saved_recipes,
        'liked_recipes': liked_recipes,
    }

    return render(request, 'recipez/user_profile.html', context=context_dict)


# Login Page
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('usernameInput')
        password = request.POST.get('passwordInput')
        remember_me = request.POST.get('rememberMe')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                if not remember_me:
                    request.session.set_expiry(0)  # set session expire time to 0
                messages.success(request, "You have been successfully logged in!")
                return redirect(reverse('recipez:index'))
            else:
                return HttpResponse("Your Recipez account is disabled.")
        else:
            # print(f"Invalid login details: {username}, {password}") # Not required, only for debugging
            messages.error(request, f"Your login details are incorrect, {username}")
            return redirect(reverse('recipez:login'))

    else:
        return render(request, 'recipez/authentication/login.html')


# User Registration Form
def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

        if registered:
            messages.success(request, "You have been successfully registered! Please log in.")
            return redirect(reverse('recipez:login'))
        else:
            messages.error(request, "Please check your registration details.")
            return redirect(reverse('recipez:register'))
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }
    return render(request, 'recipez/authentication/register.html', context=context)


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, "Successfully logged out!")
    return redirect(reverse('recipez:index'))


@login_required
def like_recipe(request, recipe_id):
    if request.method == 'POST' and is_ajax(request):
        user_profile = request.POST.get('user')
        recipe = request.POST.get('recipe')
        print(user_profile, recipe)

        u_profile = request.user.user_profile
        target_recipe = Recipe.objects.get(id=recipe)
        is_liked = request.user.user_profile.liked_recipes.filter(id=recipe_id)

        if is_liked.exists():
            u_profile.liked_recipes.remove(target_recipe)
            target_recipe.likes -= 1
        else:

templates/recipez/includes/base.html
<!DOCTYPE html>
{% load static %}
{% load recipez_template_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Recip(EZ)
        {% block title_block %}
        {% endblock %}
    </title>

    <!-- Insert CSS Files here -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/nav_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Insert Javascript files here -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

    <!-- Custom Javascript -->
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

    {% block head_block %}
    {% endblock %}
</head>

<body class="p-0 m-0 border-0 bd-example">

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler collapsed" data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse"
                type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="{% url 'recipez:index' %}">
        <img alt="" class="d-inline-block align-top" height="30" id="logo"
             src="{%  static 'images/default-monochrome-F1DEDA.svg' %}"
             width="170"> </a>

        <form role="search" method="post" action="{% url 'recipez:index' %}">
            {% csrf_token %}
            <input aria-label="Search" class="form-control me-2" placeholder="Search" type="text" name="search_content">
            <button class="btn btn-outline-success" type="submit" value="search">Search</button>
        </form>

     <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
                <li class="nav-item">
                    <a aria-current="page" class="nav-link active" href="{% url 'recipez:about' %}">About</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a aria-current="page" class="nav-link active" href="{% url 'recipez:add_recipe' %}">Write a
                            Recipe</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                           role="button">
                                
                                <img class="rounded-circle shadow-1-strong me-3"
                                     src="{{ MEDIA_URL }}{{ user.user_profile.avatar }}"
                                     alt="{{ user.username }}'s profile image"
                                     width="40"
                                     height="40"/>
                                <span class="lead">{{ user.username }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'recipez:user_profile' user.username %}">My Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'recipez:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a aria-current="page" class="nav-link active" href="{% url 'recipez:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a aria-current="page" class="nav-link active" href="{% url 'recipez:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<!-- End of Navbar -->
{% include 'recipez/includes/messages.html' %}
{% block body_block %}
{% endblock %}

<button
        type="button"
        class="btn btn-primary btn-floating btn-lg"
        id="btn-back-to-top"
        >
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-chevron-double-up" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M7.646 2.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 3.707 2.354 9.354a.5.5 0 1 1-.708-.708l6-6z"/>
            <path fill-rule="evenodd" d="M7.646 6.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 7.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
          </svg>
</button>
        

</body>


<!-- Footer -->
<footer class="text-center bg-light text-muted">

    <div class="p-4 border-bottom">

    </div>

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Recip(EZ)
                    </h6>
                    <p>
                        Enjoy Easy Cooking<br><br>Enjoy Tasting New Recipes
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Recip(EZ)
                    </h6>
                    <p>
                        <a class="text-reset" href="{% url 'recipez:index' %}">Home</a>
                    </p>
                  {% if user.is_authenticated %}
                        <p>
                            <a class="text-reset" href="{% url 'recipez:logout' %}">Logout</a>
                        </p>
                    {% else %}
                        <p>
                            <a class="text-reset" href="{% url 'recipez:register' %}">Register</a>
                        </p>
                        <p>
                            <a class="text-reset" href="{% url 'recipez:login' %}">Login</a>
                        </p>
                    {% endif %}

                    <p>
                        <a class="text-reset" href="{% url 'recipez:about' %}">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                {% if user.is_authenticated %}
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->

                        <h6 class="text-uppercase fw-bold mb-4">
                            My Profile
                        </h6>
                        <p>
                            <a class="text-reset" href="{% url 'recipez:user_profile' user.username %}">My post</a>
                        </p>
                        <p>
                            <a class="text-reset" href="{% url 'recipez:user_profile' user.username %}">My bookmark</a>
                        </p>
                        <p>
                            <a class="text-reset" href="{% url 'recipez:add_recipe' %}">Write a recipe</a>
                        </p>

                    </div>
                {% endif %}
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                    <p>Glasgow, UK</p>
                    <p>customerservice@recipez.gla.uk
                    </p>
                    <p>+ 44 074324 353 566</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
            <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2023 Copyright:
        <a class="text-reset fw-bold" href="{% url 'recipez:index' %}">recipez.gla.uk</a>
    </div>
    <!-- Copyright -->
    </section>

</footer>
<!-- Footer -->

</html>

templates/recipez/includes/messages.html
{% for message in messages %}
<div class="container py-2" id="alert">
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
        {{message}}
        <button type="button" class="close btn btn-danger btn-sm" data-dismiss="alert" aria-label="Close" id="closeAlert">
            <span aria-hidden="True">&times;</span> </button>
    </div>
  </div>
{% endfor %}